version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - run:
          name: Installing requirements.txt
          command: pip install -r requirements.txt
      - run:
          name: Running tests
          command: python3 -m unittest